version: '3'
services:
  first_app:
    container_name: teksi-bot
    build: .
    restart: always
    ports:
      - "8003:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/down_db
      SPRING_DATASOURCE_USERNAME: down_user
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
  postgres:
    container_name: postgres-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: down_db
      POSTGRES_USER: down_user
      POSTGRES_PASSWORD: root

